# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FPGrowth_ <- function(l, minimum_support) {
    .Call(`_FPGrowth_FPGrowth_`, l, minimum_support)
}

rcpp_hello <- function() {
    .Call(`_FPGrowth_rcpp_hello`)
}

